set -beEu -o pipefail

pdfunite  \
    output/extended/ES.plot_3endSupport.pdf \
    output/extended/ES.plot_5endSupport.pdf \
    output/extended/ES.plot_SJ_canonical-coverage.pdf \
    output/extended/ES.plot_SJ_canonical-coverage.zoom.pdf \
    output/extended/ES.plot_SJ_known-coverage.pdf \
    output/extended/ES.plot_SRTM_SNTM.pdf \
    output/extended/ES.plot_legend.pdf \
    output/extended/ES.plot_numGenes-numKnTrx.pdf \
    output/extended/ES.plot_numGenes-numKnTrx_tool.pdf \
    output/extended/ES.plot_numGenes-numTrx.0.pdf \
    output/extended/ES.plot_numGenes-numTrx.0_zoom.pdf \
    output/extended/ES.plot_numGenes-numTrx.pdf \
    output/extended/ES.plot_percFSM-ISM.pdf \
    output/extended/ES.plot_percFSM-ISM_tool.pdf \
    output/extended/ES.plot_percNIC-NNC.pdf \
    output/extended/ES.plot_percNIC-NNC_tool.pdf \
    ES.plots.pdf

pdfunite  \
    output/extended/Extended_Fig._4.pdf \
    output/extended/Extended_Fig._5.pdf \
    output/extended/Extended_Fig._6.pdf \
    output/extended/Extended_Fig._7.pdf \
    output/extended/Extended_Fig._8.pdf \
    output/extended/Extended_Fig._9.pdf \
    output/extended/Extended_Fig._10.pdf \
    output/extended/Extended_Fig._11.pdf \
    output/extended/Extended_Fig._12.pdf \
    output/extended/Extended_Fig._13.pdf \
    output/extended/Extended_Fig._14.pdf \
    output/extended/Extended_Fig._15.pdf \
    output/extended/Extended_Fig._16.pdf \
    output/extended/Extended_Fig._17.pdf \
    output/extended/Extended_Fig._18.pdf \
    output/extended/Extended_Fig._19.pdf \
    output/extended/Extended_Fig._20.pdf \
    output/extended/Extended_Fig._21.pdf \
    output/extended/Extended_Fig._22.pdf \
    output/extended/Extended_Fig._23.pdf \
    output/extended/Extended_Fig._24.pdf \
    output/extended/Extended_Fig._25.pdf \
    output/extended/Extended_Fig._26.pdf \
    output/extended/Extended_Fig._30.pdf \
    output/extended/Extended_Fig._31.pdf \
    output/extended/Extended_Fig._32.pdf \
    output/extended/Extended_Fig._33.pdf \
    output/extended/Extended_Fig._34.pdf \
    output/extended/Extended_Fig._35.pdf \
    output/extended/Extended_Fig._36.pdf \
    output/extended/Extended_Fig._38.pdf \
    output/extended/Extended_Fig._39.pdf \
    output/extended/Extended_Fig._40.pdf \
    output/extended/Extended_Fig._41.pdf \
    output/extended/Extended_Fig._43.pdf \
    output/extended/Extended_Fig._44.pdf \
    output/extended/Extended_Fig._45.pdf \
    output/extended/Extended_Fig._46.pdf \
    output/extended/Extended_Fig._47.pdf \
    output/extended/Extended_Fig._48.pdf \
    output/extended/Extended_Fig._49.pdf \
    output/extended/Extended_Fig._50.pdf \
    output/extended/Extended_Fig._51.pdf \
    output/extended/Extended_Fig._52.pdf \
    chg1_extended.pdf

    pdfunite  \
    output/extended/H1_mix.plot_3endSupport.pdf \
    output/extended/H1_mix.plot_5endSupport.pdf \
    output/extended/H1_mix.plot_SJ_canonical-coverage.pdf \
    output/extended/H1_mix.plot_SJ_canonical-coverage.zoom.pdf \
    output/extended/H1_mix.plot_SJ_known-coverage.pdf \
    output/extended/H1_mix.plot_SRTM_SNTM.pdf \
    output/extended/H1_mix.plot_legend.pdf \
    output/extended/H1_mix.plot_numGenes-numKnTrx.pdf \
    output/extended/H1_mix.plot_numGenes-numKnTrx_tool.pdf \
    output/extended/H1_mix.plot_numGenes-numTrx.0.pdf \
    output/extended/H1_mix.plot_numGenes-numTrx.0_zoom.pdf \
    output/extended/H1_mix.plot_numGenes-numTrx.pdf \
    output/extended/H1_mix.plot_percFSM-ISM.pdf \
    output/extended/H1_mix.plot_percFSM-ISM_tool.pdf \
    output/extended/H1_mix.plot_percNIC-NNC.pdf \
    output/extended/H1_mix.plot_percNIC-NNC_tool.pdf \
    H1_mix.plots.pdf
